# @package _global_
# Configuration for discrete model testing stage

defaults:
  - /schema/test_model_disc_schema@_here_
  - /model: ${env}
  - /test: alignment_model
  - /wandb: default
  - _self_

stage: test_model
test_model_type: discrete

test:
  tester_mode: separate
  end_to_end: false
  use_alignment_model: true
  precompute_targets: true
  log_interval: 1000
  save_interval: 1000
  visualization_format: pdf
  visualization_episode_index: 0
  visualization_steps: null #[1, 100] # Visualize steps in addition to every 1000th step
  top_k: 1
  apply_diff_highlighting: false

  dataloader:
    batch_size: 100
    enable_memory_optimization: false
    use_variation_for_all_states: false
    variations_to_use: null #["camera_variation"]
    variations_to_ignore: null
    use_encoded_targets: true

  compile:
    fullgraph: true
    dynamic: false
    backend: inductor
    mode: max-autotune
    options: null
    disable: true

data_paths:
  test_data: spar/offline_data/cube3/sim2real_2/test_100eps_10000steps_with_vars.h5
  # test_data: spar/offline_data/cube3/val_500eps_30steps_with_vars.h5

save_paths:
  images_dir: ${hydra:runtime.output_dir}/model_tests/images/${test_model_type}
  plots_dir: ${hydra:runtime.output_dir}/model_tests/plots/${test_model_type}
  metrics_dir: ${hydra:runtime.output_dir}/model_tests/metrics/${test_model_type}

pretrained_model_paths:
  encoder_path: spar/saved_models/world_models/${env.name}_world_model_disc/world_model_checkpoint_encoder.pt
  transition_model_path: spar/saved_models/world_models/${env.name}_world_model_disc/world_model_checkpoint_transition_model.pt
  decoder_path: spar/saved_models/world_models/${env.name}_world_model_disc/world_model_checkpoint_decoder.pt
  alignment_model_path: spar/saved_models/alignment_models/${env.name}_alignment_model_disc_sim2real/alignment_model_checkpoint_alignment_model.pt

model:
  continuous: null
  dqn: null

wandb:
  mode: disabled # 'online', 'offline', or 'disabled'
  job_type: test
